### ISSUE TITLE
[Suggestion] Configurable spawn rate & biome whitelist or blacklist

### ISSUE THREAD

**Issue by twome** [ThePoultryMan/Pigeons#8]
Howdy. With a few overworld biome mods installed and Wildlife + Better Animals Plus installed, the pigeons are appearing *everywhere* in every conceivable climate, and far more frequently than any other animal, let alone just birds, by a big margin. Would love to be able to tone their spawn rate down and limit them to relatively temperate biomes to better fit them in with the rest of the ecosystem.

Unrelated but I keep expecting to hear the pigeons coo - I bet there's some great free field recordings out there! imo that's a real low-hanging fruit of vibe:effort ratio.

Thanks for the very cute mod!

**Comment by ThePoultryMan** [comment]
After playing around a bit, I realized this happens with only Pleasant Pigeons as well. It should be as simple as turning the spawn rates down to fix the initial issue. However, I'm still going to look into implementing spawn configuration.

**Comment by ThePoultryMan** [comment]
The 1.19 version of the mod will allow you to use some customization using tags. There will be `low`, `medium`, and `high` for you to chose from. More information about this will be available on the wiki soon after the update is released.

_Note:_ This isn't the permanent solution, it was just brought about by code changes to the Fabric API.

**Comment by twome** [comment]
Thank you, Poultry Man! You're my hero!

**Comment by ThePoultryMan** [comment]
I'm closing this issue because version 1.5.0 contains all the changes that I'm going to make to spawn configuration. 1.5.0 allows you to configure the settings related to the tags.
